exclude: ^Eigen/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-yaml
  - repo: https://github.com/pazmivaniye/pre-commit-hooks
    rev: ac0c5b80890a4d8d2a537e6c8482f4bc1a6430af
    hooks:
      - id: check-chars
      - id: check-filenames
      - id: check-line-length
  - repo: local
    hooks:
      - id: test
        name: test
        description: Run test program
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
